### ISSUE TITLE
/bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by fmendozaro** [zgulde/tomcat-setup#8]
I got that message when i cloned the repo today, i solved it by changing the CR characters, dunno why i got them in the wrong format.
<img width="513" alt="screen shot 2017-09-01 at 8 45 47 pm" src="https://user-images.githubusercontent.com/13546596/29991974-8f055f56-8f56-11e7-8502-26ffc6d164db.png">

**Comment by zgulde** [comment]
We traced the source of this to a line in the git configuration, that is, in `~/.gitconfig` there's a line like:

```
[core]
    autocrlf = true
```

After disabling this setting and re-cloning the repo, the issue was not present
